# Generated by Django 3.1.3 on 2020-12-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('team', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=5)),
                ('gp', models.IntegerField()),
                ('mpg', models.FloatField()),
                ('ftper', models.FloatField()),
                ('ppg', models.FloatField()),
                ('rpg', models.FloatField()),
                ('apg', models.FloatField()),
                ('spg', models.FloatField()),
                ('bpg', models.FloatField()),
                ('topg', models.FloatField()),
            ],
            options={
                'db_table': 'player_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('city', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('conference', models.CharField(max_length=5)),
                ('gp', models.IntegerField()),
                ('ppg', models.FloatField()),
                ('papg', models.FloatField()),
                ('sos', models.FloatField()),
                ('wins', models.IntegerField()),
                ('loses', models.IntegerField()),
            ],
            options={
                'db_table': 'team_stats',
                'managed': False,
            },
        ),
    ]
